def get_config():
    return {
        'data_path' : 'AIProjectFabricComp\\data\\raw_data\\fabrics',
        'data_folder' : 'AIProjectFabricComp\\data',
        'training' : True,
        'batch_size' : 16,
        'feature_dim' : 1024,
        'higher_dim' : 2048,
        'num_clothes' : 14,
        'num_fabrics' : 28,
        'num_epochs' : 13,
        'dropout' : 0.1,
        'threshold' : 0.00,
        'alpha': 2.4,
        'beta' : 0.7,
        'gamma' : 2.0,
        'lr' : 1e-4,
        'max_norm': 5.0,
        'sparsity_penalty' : 0.08,
        'fabric_types' : ['acrylic', 'unknown', 'spandex', 'polyester', 'pvc', 'viscose', 'cotton', 
                          'nylon', 'wool', 'cashmere', 'rayon', 'linen', 'repreve', 'modal', 'silk', 
                          'synthetic', 'dralon', 'polyamide', 'acetate', 'angora', 'chenille cotton', 'micropoly', 
                          'crepe satin', 'fleece', 'leather', 'lut', 'supplex nylon', 'metallic fibers'],
        'fabric_counts' : {'acrylic': 70, 'unknown': 1834, 'spandex': 334, 'polyester': 647, 
                        'pvc': 3, 'viscose': 173, 'cotton': 1031, 'nylon': 49, 'wool': 151, 
                        'cashmere': 1, 'rayon': 6, 'linen': 31, 'repreve': 4, 'modal': 12, 
                        'silk': 67, 'synthetic': 2, 'dralon': 2, 'polyamide': 24, 'acetate': 2, 
                        'angora': 2, 'chenille cotton': 13, 'micropoly': 12, 'crepe satin': 12, 
                        'fleece': 5, 'leather': 16, 'lut': 4, 'supplex nylon': 6, 'metallic fibers': 2},
        'weight_decay' : 1e-4,
        'c_penalty' : 0.014,
        
}
    